[package]
name = "artistic_shuffle"
version = "1.0.0"
authors = ["Aggrathon <antonbjo@gmail.com>"]
edition = "2018"

[dependencies]
id3 = "1.6"
rand = "0.8"
pathdiff = "0.2"
lofty = "0.11"
walkdir = "2.3"

[dev-dependencies]
dirs = "4.0"
