[package]
name = "artistic_shuffle"
version = "2.0.0"
authors = ["Aggrathon <antonbjo@gmail.com>"]
edition = "2021"

[dependencies]
rand = "0.8"
lofty = "0.11"
walkdir = "2.3"
xflags = "0.3"

[dev-dependencies]
dirs = "4.0"
